create table if not exists public.company_profile (
  ticker text not null primary key,
  company_name text not null,
  description text,
  exchange text,
  website text,
  industry text,
  location text,
  range_low numeric,
  range_high numeric,
  volume numeric,
  average_volume numeric,
  x3_month_average_trading_volume numeric,
  asset_turnover_annual numeric,
  asset_turnover_ttm numeric,
  x5_day_price_return_daily numeric,
  month_to_date_price_return_daily numeric,
  x13_week_price_return_daily numeric,
  x26_week_price_return_daily numeric,
  x52_week_price_return_daily numeric,
  market_capitalization numeric,
  enterprise_value numeric,
  forward_pe numeric,
  pe_annual numeric,
  gross_margin_5y numeric,
  gross_margin_annual numeric,
  operating_margin_5y numeric,
  operating_margin_annual numeric,
  net_profit_margin_5y numeric,
  pretax_margin_5y numeric,
  pretax_margin_annual numeric,
  roe_5y numeric,
  roe_rfy numeric,
  roi_5y numeric,
  roa_5y numeric,
  roa_rfy numeric,
  dividend_per_share_annual numeric,
  dividend_growth_rate_5y numeric,
  payout_ratio_annual numeric,
  recommendation_history jsonb,
  current_recommendation text
);
